[project]
name = "booking-worker"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
    "fastapi",
    "markupsafe",
    "jinja2",
]

[dependency-groups]
dev = ["workers-py"]