# pyproject.toml
[project]
name = "fastapi-worker"
version = "0.1.0"
description = "Python fastapi example"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116",
    "jinja2>=3.1",
]

[dependency-groups]
dev = ["workers-py"]